CREATE SCHEMA DBTELEFONIA;

CREATE TABLE ENDERECO(
ID_ENDERECO INT NOT NULL PRIMARY KEY AUTO_INCREMENT 
, RUA VARCHAR(255) NOT NULL
, CEP VARCHAR(8) NOT NULL
, BAIRRO VARCHAR(255) NOT NULL
, CIDADE VARCHAR(255) NOT NULL
, UF CHAR(2) NOT NULL
, NUMERO VARCHAR(50)
);

CREATE TABLE TELEFONE(
ID_TELEFONE INT NOT NULL PRIMARY KEY AUTO_INCREMENT 
, ID_CLIENTE INT 
, DDD CHAR(3)
, NUMERO VARCHAR(15)
, STATUS_ATIVACAO BOOLEAN
, MOVEL TINYINT
);

CREATE TABLE CLIENTE(
ID_CLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT 
, ID_ENDERECO INT
, NOME VARCHAR(200)
, CPF VARCHAR(20) UNIQUE
, TELEFONE VARCHAR(20)
, STATUS_ATIVACAO TINYINT
,CONSTRAINT ID_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID_ENDERECO)
);

